# Базовые настройки
site_name: OOS
site_description: Сайт созданный с помощью MkDocs и GitHub Pages
site_author: Marrs73

# URL будет заменен после публикации
site_url: https://orderofstone.ru/

# theme: material
use_directory_urls: 




# # Подключаем тему Material
theme:
  name: material
  #custom_dir: overrides
  language: ru
  features:
    - navigation.tabs        # Вкладки в навигации
    - navigation.tabs.sticky
    - navigation.path
    # - navigation.sections    # Секции в меню
    - navigation.top         # Кнопка "наверх"
    - search.highlight       # Подсветка в поиске
    - search.suggest         # Подсказки в поиске
    - content.code.copy      # Кнопка копирования кода\
    # - toc.integrate
  palette: 
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: brown
      accent: deep orange

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: deep purple
      accent: deep purple
  font:
      code: Roboto Mono

plugins:
  - search
  - tags
  - awesome-nav
  - blogging:
      dirs:
      - Философские мысли
      - Записки читателя
      - Моя художка
      - Остальное
      locale: ru
      sort:
        from: new
        by: creation
      size: 10  # количество статей на странице

markdown_extensions:
  - markdown_captions  

extra_css:
  - stylesheets/extra.css
# nav:
#   - sort: date
 # - optimize

  
#   # Настройка цветовой схемы
#   palette:
#     - scheme: default        # Светлая тема
#       primary: indigo        # Основной цвет
#       accent: indigo         # Акцентный цвет
#       toggle:
#         icon: material/brightness-7
#         name: Переключить на темную тему
#     - scheme: slate          # Темная тема
#       primary: black
#       accent: indigo
#       toggle:
#         icon: material/brightness-4
#         name: Переключить на светлую тему

# Расширения для Markdown
# markdown_extensions:
#   - admonition               # Для заметок
#   - pymdownx.highlight:      # Подсветка кода
#       anchor_linenums: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - pymdownx.superfences
#   - pymdownx.details
#   - pymdownx.tabbed:
#       alternate_style: true

# Навигация (можно оставить автоматическую или настроить вручную)
# nav:
#   - Главная: index.md
#   - О проекте: about.md