name: Деплой MkDocs сайта

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          # Убираем cache, чтобы избежать ошибки
      
      - name: Установка MkDocs и темы
        run: |
          pip install mkdocs mkdocs-material mkdocs-bootstrap386 mkdocs-blogging-plugin mkdocs-awesome-nav
      
      - name: Сборка сайта
        run: mkdocs build --site-dir site
      
      - name: Деплой на GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages